/**
 * Deployment target configuration.
 *
 * Each entry in `deployments` represents one independent environment
 * (S3 bucket + CloudFront distribution + Route 53 alias records).
 *
 * This file is generated by `npm run configure` and should be committed
 * to source control so the CDK app is reproducible.
 */
export interface DeploymentTarget {
  /** Unique identifier for this deployment (e.g. "prod", "dev", "staging") */
  id: string;
  /** Fully qualified domain name (e.g. "app.example.com") */
  domainName: string;
  /** Route 53 hosted zone domain (e.g. "example.com") */
  hostedZoneDomain: string;
  /** Route 53 hosted zone ID */
  hostedZoneId: string;
  /** S3 bucket name for the site assets */
  bucketName: string;
  /** AWS region for the S3 bucket and ACM certificate validation */
  region: string;
}

export interface DeployConfig {
  deployments: DeploymentTarget[];
}

export function loadConfig(): DeployConfig {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const config = require("../deploy-config.json") as DeployConfig;

  if (!config.deployments || !Array.isArray(config.deployments)) {
    throw new Error(
      "deploy-config.json must contain a `deployments` array. Run `npm run configure` first.",
    );
  }

  for (const d of config.deployments) {
    if (!d.id || !d.domainName || !d.hostedZoneDomain || !d.hostedZoneId || !d.bucketName) {
      throw new Error(
        `Deployment "${d.id || "(unnamed)"}" is missing required fields. Run \`npm run configure\` to fix.`,
      );
    }
  }

  return config;
}
